version: '3.8'

services:
  backend:
    build: ./backend-node
    container_name: vendor-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    volumes:
      - ./backend-node/data:/app/data

  frontend:
    build: ./frontend
    container_name: vendor-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
